[package]
name = "eyeliner"
version = "0.1.0"
authors = ["Dylan Frankland <dylan@frankland.io>"]
description = "A CSS inliner for making emails."
repository = "https://github.com/dfrankland/eyeliner"
readme = "README.md"
keywords = ["html", "css", "email", "inliner"]
categories = ["email", "development-tools", "parsing", "rendering", "template-engine"]
license = "MIT"

[dependencies]
kuchiki = "0.6.0"
servo-css-parser = { git = "https://github.com/victorporof/servo-css-parser" }

# Required for `servo` to compile
[replace]
"serde:1.0.23" = { git = "https://github.com/gankro/serde", branch = "deserialize_from_enums3" }
"serde_derive:1.0.23" = { git = "https://github.com/gankro/serde", branch = "deserialize_from_enums3" }
